name: gh-pages

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
  schedule:
    - cron: '0 12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Generate RSS
        run: pnpm run rss

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
